name = Terras Abertas
title = Terras Abertas
author = Tedi Group
description = An open-world sandbox game focused on exploration, building and total freedom.
engine = luanti

mods = linguagem, ta_base, jogador, conquistas
