enable_damage = true
creative_mode = true
mod_storage_backend = sqlite3
auth_backend = sqlite3
backend = sqlite3
player_backend = sqlite3
gameid = Terras Abertas
world_name = papel de parede
server_announce = false
